### ISSUE TITLE
Still Having Problems with Environment Variables

### ISSUE THREAD

**Issue by konrad51** [redraw/wizmusic#2]
Still trying to get this to work. Using windows 10. am using... powershell $Env:SPOTIPY_CLIENT_ID='7644a895f19b4a9d8d97b9738b899476' Same with client secret and redirect uri. This is what I get "C:\Users\schultz\AppData\Local\Programs\Python\Python39\Scripts>wizmusic
Missing envs: {'SPOTIPY_REDIRECT_URI', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_CLIENT_ID'}. Please help .Thank you.

**Comment by redraw** [comment]
Hey hi, let's continue in #1
